### ISSUE TITLE
Disabling 'Wrote ...'

### ISSUE THREAD

**Issue by jojojames** [nathankot/company-sourcekit#18]
Wrote /var/folders/k2/y7hdq90906d_5pgbt3_pt9jw0000gn/T/sourcekitten37241uWD [11 times]
Saving file /Users/**/messagebottle/AppDelegate.swift...
Wrote /Users/**/AppDelegate.swift
Wrote /var/folders/k2/y7hdq90906d_5pgbt3_pt9jw0000gn/T/sourcekitten37241uWD [15 times]
Saving file /Users/**/AppDelegate.swift...
Wrote /Users/**/AppDelegate.swift
Wrote /var/folders/k2/y7hdq90906d_5pgbt3_pt9jw0000gn/T/sourcekitten37241uWD [18 times]

  (setq company-sourcekit-verbose nil)
  (setq sourcekit-verbose nil)

are nil.

Seems to be writing to a file after every (single) character is typed.

**Comment by nathankot** [comment]
Hey @jojojames, sourcekit needs to be given a saved file in order to do completion so we save the buffer to a tmp buffer each time. This is the same way completion works in Xcode except it auto-saves the original buffer consistently.

I don't think theres a good way to silence the write logs, any improvements or suggestions to this are well accepted :)
